import { API_PATH } from '@/module/config/index';
export const materialListUrl = `${API_PATH}/fdstp/a/driver/base/queryTrainingList`;
export const materialDetailUrl = `${API_PATH}/fdstp/a/driver/base/queryTrainingContent`;
export const trainLearnSignUrl = `${API_PATH}/fdstp/a/driver/base/updateTrainingLearnSign`;
export const loginUrl = `${API_PATH}/fdstp/a/login`;
export const truckPhotoUploadUrl = `${API_PATH}/fdstp/a/driver/base/truckDepartCheckPhotoUpload`;
export const truckCheckListUrl = `${API_PATH}/fdstp/a/driver/base/truckCheckList`;
export const examQuestionUrl = `${API_PATH}/fdstp/a/driver/base/examQuestion`;
export const submitQuestionUrl = `${API_PATH}/fdstp/a/driver/base/examAnswerUpload`;
export const updatePhoto = `${API_PATH}/fdstp/fdstp/user/updatePhoto`;
export const getPhoto = `${API_PATH}/fdstp/fdstp/user/queryPhoto`;
